version: '3.9'

services:

  database:
    image: mysql:8.0.33
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lportal
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --character-set-client-handshake=FALSE --lower-case-table-names=0
    volumes:
       - ./docker-compose/database-dump/:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  liferay:
    image: liferay/dxp:2024.q2.6
    environment:
      - LIFERAY_JPDA_ENABLED=true
      - LIFERAY_JVM_OPTS=-Xms3g -Xmx4g
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME=com.mysql.cj.jdbc.Driver
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL=jdbc:mysql://database/lportal?characterEncoding=utf8&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&serverTimezone=GMT&useFastDateParsing=false&useUnicode=true
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME=root
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD=root
      - LIFERAY_MODULE_PERIOD_FRAMEWORK_PERIOD_PROPERTIES_PERIOD_OSGI_PERIOD_CONSOLE=0.0.0.0:11311
      - LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_DELAY=20
      - LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_MAX_PERIOD_RETRIES=5
      - LIFERAY_UPGRADE_PERIOD_DATABASE_PERIOD_AUTO_PERIOD_RUN=true
      - LIFERAY_UPGRADE_PERIOD_REPORT_PERIOD_ENABLED=true
      # - LIFERAY_UPGRADE_PERIOD_LOG_PERIOD_CONTEXT_PERIOD_ENABLED=true
      - LIFERAY_COMPANY_PERIOD_DEFAULT_PERIOD_WEB_PERIOD_ID=wnbizlink.com
      - LIFERAY_COMPANY_PERIOD_DEFAULT_PERIOD_NAME=wnbizlink
      - LIFERAY_DL_PERIOD_STORE_PERIOD_IMPL=com.liferay.portal.store.file.system.AdvancedFileSystemStore
      - LIFERAY_SETUP_PERIOD_WIZARD_PERIOD_ENABLED=false
      - LIFERAY_COMPANY_PERIOD_LOGIN_PERIOD_PREPOPULATE_PERIOD_DOMAIN=false
      - LIFERAY_COMPANY_PERIOD_SECURITY_PERIOD_STRANGERS_PERIOD_URL=/registration
      - LIFERAY_DEFAULT_PERIOD_LANDING_PERIOD_PAGE_PERIOD_PATH=/group/wnbizlink/home
      - LIFERAY_TERMS_PERIOD_OF_PERIOD_USE_PERIOD_REQUIRED=false
      - LIFERAY_LOCALES=en_US
      - LIFERAY_PASSWORDS_PERIOD_ENCRYPTION_PERIOD_ALGORITHM_PERIOD_LEGACY=SHA
      - LIFERAY_AUTH_PERIOD_LOGIN_PERIOD_URL=/web/wnbizlink/login
      - LIFERAY_TEMPLATE_PERIOD_ENGINE_PERIOD_SERVICE_PERIOD_LOCATOR_PERIOD_RESTRICT=false
      - LIFERAY_MODULE_PERIOD_FRAMEWORK_PERIOD_WEB_PERIOD_GENERATOR_PERIOD_GENERATED_PERIOD_WABS_PERIOD_STORE=true
    ports:
      - "8080:8080"
      - "11311:11311"
      - "8000:8000"
    volumes:
      - ./docker-compose/liferay-files:/mnt/liferay/files
      - ./docker-compose/liferay-scripts:/mnt/liferay/scripts
      - ./bundles/deploy:/mnt/liferay/deploy
      # - ./bundles/osgi/modules:/opt/liferay/osgi/modules
      - ./bundles/osgi/configs:/opt/liferay/osgi/configs
      - ./bundles/osgi/war:/opt/liferay/osgi/war
      - ./bundles/logs:/opt/liferay/logs
      - ./bundles/data/document_library:/opt/liferay/data/document_library
    depends_on:
      - database
      - search

  search:
    image: baseline/elasticsearch
    build: ./docker-compose/elasticsearch/
    environment:
      - cluster.name=LiferayElasticsearchCluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - "node.name=es-node1"
    volumes:
      - ./bundles/data/elasticsearch-data:/usr/share/elasticsearch/data
